feature/PRA-33 Input
26-chips/26-chips-pacman pull request #11
Opened 2023-05-27 17:13 UTC by gitnbrsp

### Какую задачу решаем
Компонент Input

### Скриншоты/видяшка (если есть)
[Screencast from 27.05.2023 20:07:22.webm](https://github.com/26-chips/26-chips-pacman/assets/126918257/7bbb92de-29f0-41a9-b3fc-ab25dc63d2f1)

### TBD (если есть)
Сейчас послушаю про все косяки, поправлю остальное и залью отдельными PR

2023-05-27 17:20 UTC, Abricos78 commented on packages/client/src/components/Input/input.module.scss
> +.input-container {
Не вижу смысла в префиксе input, так как у нас модули и стили никак пересекаться не будут, плюс сам файл со стилями лежит в одноименной папке, получается масло масленное

2023-05-27 17:23 UTC, Abricos78 commented on packages/client/src/components/Input/Input.tsx
> +import React, { ReactNode, useState } from 'react';
C 17 версии Реакт, его не нужно импортировать в файлы, у нас 18

2023-05-27 17:31 UTC, Abricos78 commented on packages/client/src/components/Input/Input.tsx
> +        className={cn(styles.inputUnderlined, { [styles.danger]: !isValid })}>
Надо будет настроить eslint и prettier, чтобы правильные переносы были. Но на будущее, так код читается не очень, так как не видно где заканчивается тег. Лучше написать вот так 
`<label`
 &nbsp; `className={...}`
 `>`
  &nbsp;  &nbsp; `content`
  `</label>`

2023-05-27 17:33 UTC, Abricos78 commented on packages/client/src/components/Input/input.module.scss
> +  input {
По моему мнению, лучше задать тегу input класс .input и использовать его уже здесь, не трогая теги вообще

2023-05-27 17:42 UTC, Abricos78 commented on packages/client/src/components/Input/input.module.scss
> +.input-underlined:not(.input-danger), .input-filled:not(.input-danger) {
Вот здесь перемудрил, утилита classnames не добавит класс если передано falsy-значение, поэтому можно обойтись обычной вложенностью scss и не использовать псевдоклассы, так как чем сложнее селектор, тем он более трудоемкий с точки зрения производительности

2023-05-27 17:44 UTC, Abricos78 commented on packages/client/src/components/_components.scss
> +@import "../constants";
Тут я бы хотел услышать твою аргументацию зачем нужен этот общий файл со стилями, особенно когда вижу в нем определенные теги по типу input и textarea, ведь для них будет собственная директория

2023-05-27 17:47 UTC, Abricos78 commented on packages/client/src/pages/UIPage/UIPage.tsx
> +      <h1>UI Page</h1>
Я так понимаю это страница у нас вместо storybook-а?)))

2023-05-27 17:51 UTC, Abricos78 commented on packages/client/src/components/Input/Input.tsx
> +  deleteSymbol?: string | ReactNode;
deleteSymbol излишняя функциональность, я бы перенес это в компоненту

2023-05-27 17:55 UTC, Abricos78 commented on packages/client/src/components/Input/Input.tsx
> +  validateFn?: (s: string) => boolean;
С учетом того что будем использовать formik, валидация в компоненте излишняя, так же как и isValid, потому что мы будем передавать errorMessage, а значит если errorMessage === true, то isValid === false. Но здесь я бы хотел послушать мнение остальных участников, мб я не прав

2023-05-27 18:06 UTC, Abricos78 commented on packages/client/src/components/Input/input.module.scss
> +@import "../../constants";
Там Юля добавила алисы, я бы вынес туда же путь до папки с константами

2023-05-27 18:07 UTC, gitnbrsp commented on packages/client/src/components/Input/input.module.scss
> +.input-underlined:not(.input-danger), .input-filled:not(.input-danger) {
Я сначала это написал, а потом предложили использовать classnames)

2023-05-27 18:08 UTC, gitnbrsp commented on packages/client/src/components/_components.scss
> +@import "../constants";
Это скорее предложение вынести общие стили компонентов, сомневаюсь что мы где-то еще будем использовать их по другому стилизованые. Может не в таком виде

2023-05-27 18:08 UTC, gitnbrsp commented on packages/client/src/pages/UIPage/UIPage.tsx
> +      <h1>UI Page</h1>
Ну мне показалось да, вроде об этом говорили на созвоне

2023-05-27 18:09 UTC, Abricos78 commented on packages/client/src/components/Input/input.module.scss
> +.input-underlined:not(.input-danger), .input-filled:not(.input-danger) {
Ааа, тогда понял)))

2023-05-27 18:11 UTC, gitnbrsp commented on packages/client/src/components/Input/Input.tsx
> +  validateFn?: (s: string) => boolean;
Вообще изначально я задумывал это как заглушку до того как реализуем валидацию

2023-05-27 18:11 UTC, Abricos78 commented on packages/client/src/components/_components.scss
> +@import "../constants";
Я бы предложил пока с этим повременить, когда будет хотя бы тройка компонент, можно будет посмотреть что будет( и если ) повторяться и вынести в общее, сейчас я кроме базовых hide, show ничего придумать не могу

2023-05-27 18:40 UTC, Futuringer requested changes
Не забудь еще пожалуйста от ветки sprint_5 обеовиться

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +export const Input = (props: InputProps) => {
export interface Props extends React.InputHTMLAttributes<HTMLInputElement> нужно наследоваться от компонента дефолтного инпута тк нам нужны все пропсы, которые может принять обычный инпут, onBlur, name, disabled, maxLength и тд, остальные прпсы передаем через деструктуризацию {...props}

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +        <span className={cn(styles.helper)}>{errorMessage}</span>
Тут и ниже, если 1 класс, то не нужно использовать cn, просто className={styles.helper}

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/Input/input.module.scss
> +  top: 1.4rem;
везде в px, letterspacing в em

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +  const [val, setValue] = useState(value);
эти пропсы убираем, состоянием будем управлять извне

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +          {deleteSymbol || ' '}
если нет deleteSymbol то не отрисовываем спан вообще, сейчас отрисовывается с пустым значение

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +            [styles.inputLabelUp]: val.length > 0 && !isLabelStatic,
не вижу на макетах кейса когда лэйбл снизу и он не ошибка. Плюс сейчас он накладывается на сообщение об ошибке, я предлагаю убрать эту логику

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/components/_components.scss
> +@import "../constants";
Поддерживаю, предлагаю все стили перенести в инпут, не очень интуитивно получилось

2023-05-27 18:40 UTC, Futuringer commented on packages/client/src/pages/UIPage/UIPage.tsx
> +      <h1>UI Page</h1>
я себе так представлял, со сторибуком уж вряд ли будем возиться

2023-05-27 20:46 UTC, gitnbrsp commented on packages/client/src/components/Input/Input.tsx
> +            [styles.inputLabelUp]: val.length > 0 && !isLabelStatic,
inputLabelUp поднимает верхний лейбл при вводе текста если это не форма ЛК (Input personal cabinet на макете, не двигается при вводе). Не понял что ты имеешь ввиду под тем что он не ошибка и где он накладывается, нижнее сообщение при ошибке - helper, переименовал в error-message, а то действительно не очень понятно

2023-05-27 21:33 UTC, gitnbrsp commented on packages/client/src/components/Input/Input.tsx
> +            [styles.inputLabelUp]: val.length > 0 && !isLabelStatic,
Пока просто оставил их в поднятом и обычном состоянии

2023-05-27 21:42 UTC, gitnbrsp commented on packages/client/src/components/Input/Input.tsx
> +  deleteSymbol?: string | ReactNode;
пока оставил

2023-05-28 07:38 UTC, Abricos78 commented on packages/client/src/components/Input/Input.tsx
> +          })}></input>
Если у тега нет контента внутри, то можно его закрывать просто добавив слеш в конце
`<input className={...} />`

2023-05-28 07:41 UTC, Abricos78 approved these changes

2023-05-28 08:43 UTC, Futuringer requested changes

2023-05-28 08:43 UTC, Futuringer commented on packages/client/src/components/Input/input.module.scss
> +.underlined, .filled {
filled класс отсутствует в разметке и ничего не делает, .underlined класс ничего не делает, его можно просто удалить

2023-05-28 08:43 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +        {deleteSymbol ? (
{deleteSymbol && (
          <span className={styles.clear}>{deleteSymbol}</span>
        )} используем такой синтаксис, если на не нужно второе значение тернарного оператора

2023-05-28 08:43 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +          <span className={styles.clear}>{deleteSymbol}</span>
кнопка удаления никогда не сможет работать, в нее ничего не пробрасывается

2023-05-28 08:43 UTC, Futuringer commented on packages/client/src/components/Input/Input.tsx
> +          {otherProps.title}
вытаскиваем все пропсы через деструктуризацию

2023-05-28 09:25 UTC, gitnbrsp commented on packages/client/src/components/Input/Input.tsx
> +            [styles.inputLabelUp]: val.length > 0 && !isLabelStatic,
нашел в чем проблема, top: auto у firefox и chrome по разному отображается, заменил на 0

2023-05-28 10:17 UTC, gitnbrsp commented on packages/client/src/components/Input/Input.tsx
> +          <span className={styles.clear}>{deleteSymbol}</span>
пока добавил удаление через ref внутри компонента

2023-05-28 10:20 UTC, Abricos78 approved these changes

2023-05-28 11:45 UTC, merged

2023-05-30 19:12 UTC, gitnbrsp commented on packages/client/vite.config.ts
> +  css: {
эту секцию добавить