Feature/pra 28 button
26-chips/26-chips-pacman pull request #12
Opened 2023-05-28 13:59 UTC by Abricos78

### Какую задачу решаем
Добавил ui-компонент Button, плюс небольшой рефакторинг

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-05-28 17:15 UTC, gitnbrsp approved these changes

2023-05-28 17:15 UTC, gitnbrsp commented on packages/client/src/components/Button/index.tsx
> +    width,
Что-то я не подумал передавать размеры в пропсах, надо тоже так сделать

2023-05-29 06:47 UTC, Futuringer commented on packages/client/src/components/Button/index.tsx
> +    width,
Не, подожди, я сейчас отпишу в комментах как мне видится нужно делать

2023-05-29 07:15 UTC, Futuringer requested changes
На макетах еще есть кнопка прозрачная с обводкой синей просто

2023-05-29 07:15 UTC, Futuringer commented on packages/client/src/components/Button/index.tsx
> +      className={cn(styles.button, {
через деструктцризацию нужно вытащить пропс className и конкатенировать его с классом кнопки, в этот пропс мы сможет передавать стили которые хотим изменить

2023-05-29 07:15 UTC, Futuringer commented on packages/client/src/components/Button/index.tsx
> +  width?: number;
предлагаю убрать width и height, height сделать по умолчанию как высота на макетах, width сделать 100%,  ширина будет регулироваться за счет контейнера, чтобы можно было просто кинуть 2 баттона в контейнер, прописать контейнеру flex, gap: 10px и баттоны автоматически стали адаптивными. Если будет нужна другая высота и ширина - изменим ее через пропс classname

2023-05-29 07:15 UTC, Futuringer commented on packages/client/src/components/Button/index.tsx
> +        width: width && `${width}px`,
Выше отписал, как я предлагаю быть с шириной, вообще до последнего  стараемся избегать inline стилей, их потом фиг перезапишешь

2023-05-29 07:15 UTC, Futuringer commented on packages/client/src/components/Button/styles.module.scss
> +  &:disabled {
pointer-events: none

2023-05-29 08:03 UTC, Futuringer approved these changes

2023-05-29 08:04 UTC, merged