init
26-chips/26-chips-pacman pull request #13
Opened 2023-05-28 20:18 UTC by gitnbrsp

### Какую задачу решаем
Компонент Checkbox
### Скриншоты/видяшка (если есть)

### TBD (если есть)
В ожидании мерджа рефактора в ПР кнопки

2023-05-28 21:25 UTC, Abricos78 commented on packages/client/src/components/Checkbox/checkbox.module.scss
> +.checkmark::after {
Так как селектор один, а значит стиль применяется только к одному конкретному элементу, можно его поместить в сам класс .checkmark, через  `&::after { ... }`

2023-05-30 08:23 UTC, Abricos78 approved these changes

2023-05-30 18:05 UTC, Futuringer requested changes
import { InputHTMLAttributes } from 'react';
import styles from './checkbox.module.scss';

export const Checkbox = (props: InputHTMLAttributes<HTMLInputElement>) => {
  return (
    <div className={styles.container}>
      <label className={styles.checkbox}>
        <input
          {...props}
          type="checkbox"
          className={styles.input}
        />
        <span className={styles.checkmark} />
      </label>
    </div>
  );
};
компонент будет выглядеть вот так

2023-05-31 07:31 UTC, Futuringer approved these changes
Апрувнул, реши пожалуйста конфликты с веткой и можешь сам примерджить со сквош коммитом

2023-05-31 19:45 UTC, merged