feature/PRA-35_Switch
26-chips/26-chips-pacman pull request #14
Opened 2023-05-28 20:38 UTC by gitnbrsp

### Какую задачу решаем

Компонент Switch

### Скриншоты/видяшка (если есть)

### TBD (если есть)

В ожидании мерджа рефактора в ПР кнопки

2023-05-28 21:32 UTC, Abricos78 commented on packages/client/src/components/Switch/Switch.tsx
> +          defaultChecked={defaultChecked}
Я бы предложил вообще избавиться от defaultChecked, так как у нас есть свойство checked и мы можем передавать его в Switch хоть true, хоть false, что и будет своего рода default поведением

2023-05-28 21:35 UTC, Abricos78 commented on packages/client/src/components/Switch/switch.module.scss
> +.slider::before {
Используй лучше вот такой синтаксис `&::before`, а то на css больно похоже)))

2023-05-29 19:45 UTC, gitnbrsp commented on packages/client/src/components/Switch/Switch.tsx
> +          defaultChecked={defaultChecked}
ну без defaultChecked не получилось обойтись, оказаось он при начальном рендере используется, а checked игнорируется, так что передаю checked и в defaultChecked

2023-05-30 11:46 UTC, juliastetskaya commented on packages/client/src/components/Switch/Switch.tsx
> +          defaultChecked={defaultChecked}
В консоле сейчас ошибка, потому что должен быть либо `checked`, либо `defaultChecked`. Как ты видишь, что checked игнорируется? Вроде все хорошо работает без него

2023-05-30 11:54 UTC, juliastetskaya commented on packages/client/src/components/Switch/Switch.tsx
> +          onClick={toggleCheckbox}
Состояние должно меняться по onChange, а не onClick

2023-05-30 18:00 UTC, Futuringer requested changes

2023-05-30 18:00 UTC, Futuringer commented on packages/client/src/components/Switch/Switch.tsx
> +          onClick={toggleCheckbox}
тут не будет ни checked={isChecked} ни onClick ни onChange

2023-05-30 22:46 UTC, gitnbrsp commented on packages/client/src/components/Switch/Switch.tsx
> +          defaultChecked={defaultChecked}
неправильно понял описание в документации, там говорится что `defaultChecked` используется только при начальном рендере, а `checked` всегда, поправил

2023-05-31 21:04 UTC, gitnbrsp commented on packages/client/src/components/Switch/switch.module.scss
> +  &:has(input:checked) {
Пока оставил переключение через :has, если надо найду или сделаю полифил на js

2023-06-01 06:25 UTC, Futuringer approved these changes

2023-06-01 06:26 UTC, merged