feature/PRA-39_Tabs
26-chips/26-chips-pacman pull request #15
Opened 2023-05-28 20:44 UTC by gitnbrsp

### Какую задачу решаем

Компонент Tabs

### Скриншоты/видяшка (если есть)

### TBD (если есть)

В ожидании мерджа рефактора в ПР кнопки

2023-05-28 21:47 UTC, Abricos78 commented on packages/client/src/components/Tabs/Tabs.tsx
> +    setCurrentTab((e.target as HTMLLIElement).innerText.toString());
innerText же и так возвращает строку, зачем дополнительно преобразовывать к строке?

2023-05-29 16:01 UTC, gitnbrsp commented on packages/client/src/components/Tabs/Tabs.tsx
> +    setCurrentTab((e.target as HTMLLIElement).innerText.toString());
Было value, ts ругался что может быть undefined, заменил на innerText и не убрал toString. Поправил, спасибо

2023-05-30 08:21 UTC, Abricos78 approved these changes

2023-05-30 11:33 UTC, juliastetskaya commented on packages/client/src/components/Tabs/tabs.module.scss
> +        border-top-left-radius: 5px;
На макете скругление у углов больше - 8px
И его можно задать одним свойством `border-radius: 8px 0 0 8px`

2023-05-30 11:33 UTC, juliastetskaya commented on packages/client/src/components/Tabs/tabs.module.scss
> +    list-style: none;
Интересно, почему `list-style` прописывается для звездочки, а не напрямую для `ul`? Заодно можно и дефолтные маржины и паддинги скинуть

2023-05-30 17:51 UTC, Futuringer requested changes
20:29:46 [vite] warning: Top-level "this" will be replaced with undefined since this file is an ECMAScript module
36 |          }),
37 |          key: tab,
38 |          __self: this,
   |                  ^
39 |          __source: {
40 |            fileName: _jsxFileName,
ошибка в кончоли при запуске проекта, поправь плз

2023-05-30 17:51 UTC, Futuringer commented on packages/client/src/components/Tabs/Tabs.tsx
> +  const [currentTab, setCurrentTab] = useState(activeTab);
перенести эту логику вне компонента, компонент принимает activeTab и setActiveTab

2023-05-30 17:51 UTC, Futuringer commented on packages/client/src/components/Tabs/Tabs.tsx
> +            className={cn(styles.li, { [styles.active]: tab === currentTab })}
Ищем нужный таб не по контенту а по номеру, activeTab хранит номер в массиве tabNames, setActiveTab устанавливает номер

2023-05-30 17:51 UTC, Futuringer commented on packages/client/src/components/Tabs/Tabs.tsx
> +  const toggleTab = (e: MouseEvent<HTMLUListElement>) => {
когда сделаем через номера - отпадет необходимость в этой заглушке, так что давай удалим

2023-05-30 21:19 UTC, gitnbrsp commented on packages/client/src/components/Tabs/tabs.module.scss
> +    list-style: none;
откуда-то скопировал не подумав) спасибо

2023-05-30 22:14 UTC, gitnbrsp commented
С ошибкой в консоли вроде не мой косяк, но конфиг поправил, но не знаю насколько это оправдано, вот ссылка на Issue https://github.com/vitejs/vite/discussions/8640

2023-05-31 07:17 UTC, Futuringer approved these changes

2023-05-31 07:29 UTC, merged