PRA-40 Textarea
26-chips/26-chips-pacman pull request #16
Opened 2023-05-28 20:47 UTC by gitnbrsp

### Какую задачу решаем

Компонент Checkbox

### Скриншоты/видяшка (если есть)

### TBD (если есть)

В ожидании мерджа рефактора в ПР кнопки

2023-05-28 21:55 UTC, Abricos78 commented on packages/client/src/components/Textarea/Textarea.tsx
> +        [styles.warning]: errorMessage?.length,
Необязательно проверять на длину, если там будет undefined или пустая строка, то это все falsy значения, а значит класс применен не будет

2023-05-29 18:46 UTC, juliastetskaya commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const { errorMessage, allowedCharactersNumber, ...otherProps } = props;
Может будем сразу деструктурировать просы?
```suggestion
  export const Textarea = ({ errorMessage, allowedCharactersNumber, ...otherProps }: TextareaProps): JSX.Element => {
```

2023-05-29 20:29 UTC, gitnbrsp commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const { errorMessage, allowedCharactersNumber, ...otherProps } = props;
думаю пока так оставить, потом если решм переделать то одним коммитом и ПР вольем из какой-нибудь ветки fix, так как все равно править в том что уже залито нужно, уточню в пачке

2023-05-30 08:18 UTC, Abricos78 approved these changes

2023-05-30 11:14 UTC, juliastetskaya requested changes

2023-05-30 11:14 UTC, juliastetskaya commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const { errorMessage, className, allowedCharactersNumber, ...otherProps } =
Может стоит для `allowedCharactersNumber` задать дефолтное значение, чтобы каждый раз не передавать?

2023-05-30 11:14 UTC, juliastetskaya commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const { errorMessage, className, allowedCharactersNumber, ...otherProps } =
Не совсем понятно зачем показывать `allowedCharactersNumber`, если напечатать юзер сможет столько, сколько захочет

2023-05-30 17:28 UTC, Futuringer requested changes

2023-05-30 17:28 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const [val, setValue] = useState('');
сделать как в инпуте, убрать этот стейт

2023-05-30 17:28 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +          {val.length}/{allowedCharactersNumber}
доставать value из ref, можно было бы и из пропсов если были бы уверены что будет контролируемый компонент всегда

2023-05-30 17:28 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +        className={cn(styles.textarea, className)}
добавить maxLength={allowedCharactersNumber}

2023-05-30 19:29 UTC, gitnbrsp commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const { errorMessage, className, allowedCharactersNumber, ...otherProps } =
забыл добавить, спасибо

2023-05-30 21:01 UTC, gitnbrsp commented on packages/client/src/components/Textarea/Textarea.tsx
> +        className={cn(styles.textarea, className)}
Убрал вообще allowedCharactersNumber, не подумал про maxLength, спасибо, получалось лишнее свойство

2023-05-31 06:34 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +          {val.length}/{allowedCharactersNumber}
да, ты прав, я тупанул, что мы тут не проверяем а отображаем, давай тогда тут отображать value/{allowedCharactersNumber}, value из пропсов которое приходит, так будет работать только когда компонент контроллируемый, но мы так и будем его использовать

2023-05-31 07:02 UTC, Futuringer requested changes

2023-05-31 07:02 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +    value = '',
ты достал value из пропсов, но не добавил его в компонент, value больше нет в ...restProps

2023-05-31 07:11 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +          {val.length}/{allowedCharactersNumber}
да, я ошибся, забыл что мы рендерим а не проверяем тут. Тут мы будем доставать value из пропсов {value.toString().length}/{maxLength}

2023-05-31 07:15 UTC, Futuringer requested changes
<Textarea value={state} onChange={(e)=>setState(e.target.value)}/> вот так мы используем компонент

вот так он в итоге должен выглядеть 
    <div
      className={cn(styles.container, {
        [styles.warning]: errorMessage?.length,
      })}>
      <textarea
        {...otherProps}
        value={value}
        maxLength={maxLength}
        className={cn(styles.textarea, className)}
        ></textarea>
      <div className={styles.counter}>
        <span>
          {value.toString().length}/{maxLength}
        </span>
      </div>
      <span className={styles.errorMessage}>{errorMessage}</span>
    </div>

2023-05-31 07:15 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
> +  const [counter, setCounter] = useState(value.toString().length);
handleChange будет удален, этот стейт не пнадобится

2023-05-31 07:15 UTC, Futuringer commented on packages/client/src/components/Textarea/Textarea.tsx
>          onChange={handleChange}></textarea>
удалить эту строку, handleChange мы принимаем от родителя

2023-06-01 06:44 UTC, merged