feature/PRA-20-leaderboard
26-chips/26-chips-pacman pull request #22
Opened 2023-06-01 18:28 UTC by juliastetskaya

### Какую задачу решаем
Верстка лидерборда

### Скриншоты/видяшка (если есть)
![Screenshot 2023-06-01 at 9 27 31 PM](https://github.com/26-chips/26-chips-pacman/assets/30536011/52f46e32-ddcd-40b5-9b4c-648eb1b66a54)

### TBD (если есть)

2023-06-02 07:06 UTC, Abricos78 approved these changes

2023-06-02 09:40 UTC, Futuringer requested changes

2023-06-02 09:40 UTC, Futuringer commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +const MOCK_DATA = [
давай добавим сюда сразу поле avatar, я так понимаю оно точно будет закреплено за каждым пользователем, просто можно null туда. Рейтинг по идее это тоже параметр который закреплен за каждым элементом в таблице

2023-06-02 09:40 UTC, Futuringer commented on packages/client/src/pages/LeaderboardPage/LeaderboardRow.tsx
> +        <img src={defaultAvatar} alt="default avatar" />
а тут если есть аватар, то его, если нет то заглушку

2023-06-02 09:40 UTC, Futuringer commented on packages/client/src/pages/LeaderboardPage/types.ts
> +};
Не понимаю  замысел этого файла. Пропсы мы сейчас описываем в файлах компонентов, если подразумевается что это типы  сущностей, которые мы потом перенесем в store/models, то во первых они должны называться без слова Props в конце, должны типизировать нашу дату(пока что MOCK_DATA). 
мне кажется должно быть так
 export type LeaderboardData = {
  place: number;
  name: string;
  score: number;
  avatar: string;
};

const MOCK_DATA:LeaderboardData[]  = [
...
];

в компоненте строки
interface LeaderboardRowProps = LeaderboardData

2023-06-02 09:40 UTC, Futuringer commented on packages/client/src/pages/LeaderboardPage/types.ts
> +};
может чет не понимаю, готов обсудить

2023-06-03 07:57 UTC, juliastetskaya commented on packages/client/src/pages/LeaderboardPage/LeaderboardPage.tsx
> +const MOCK_DATA = [
Добавила

2023-06-03 07:58 UTC, juliastetskaya commented on packages/client/src/pages/LeaderboardPage/types.ts
> +};
Все правильно ты понял. Просто я пока не вводила как таковую сущность, потому что непонятно какие там вообще поля будут. Поправила, чтобы было очевиднее. Спасибо.

2023-06-03 11:33 UTC, Futuringer approved these changes

2023-06-03 11:33 UTC, merged