feature/PRA-24 End game screen
26-chips/26-chips-pacman pull request #25
Opened 2023-06-02 16:20 UTC by gitnbrsp

### Какую задачу решаем

Экран завершения игры

### Скриншоты/видяшка (если есть)
![image](https://github.com/26-chips/26-chips-pacman/assets/126918257/d7eb41bb-89fb-476f-b2fc-6ebb94b24019)

### TBD (если есть)

2023-06-02 19:01 UTC, gitnbrsp commented on packages/client/src/components/Modal/styles.module.scss
> +  position: fixed;
была проблема с отображением при прокрутке

2023-06-02 19:59 UTC, gitnbrsp commented on packages/client/src/components/Modal/index.tsx
> +  children?: ReactNode;
да, ты прав, я сначала хотел наследоваться от пропсов модалки, забыл убрать, спасибо

2023-06-02 20:13 UTC, Abricos78 approved these changes

2023-06-03 10:33 UTC, Futuringer requested changes

2023-06-03 10:33 UTC, Futuringer commented on packages/client/src/components/EndGameScreen/EndGameScreen.tsx
> +function EndGameComponent({
думаю мы будет придерживаться схемы 1 компонента в файле, если уж совсем нет причин сделать по-другому. Вынеси пожалуйста этот компонент в файл EndGameScreen/components/EndGameComponent, и файл стилей рядом

2023-06-03 10:33 UTC, Futuringer commented on packages/client/src/components/EndGameScreen/EndGameScreen.tsx
> +}: EndGameComponentProps & ModalProps) => {
Там, где добавляешь компонент на страницу ругается что нет детей в передаваемых пропсах нам их тут и не нужно ожидать
```suggestion
}: EndGameComponentProps & Omit<ModalProps, 'children'>) => {
```

2023-06-03 10:33 UTC, Futuringer commented on packages/client/src/components/EndGameScreen/endgamescreen.module.scss
давай переименуем в camelCase

2023-06-04 08:07 UTC, Futuringer approved these changes

2023-06-04 08:08 UTC, merged