Feature/PRA-21 Main page
26-chips/26-chips-pacman pull request #26
Opened 2023-06-03 07:32 UTC by gitnbrsp

### Какую задачу решаем
Страница начала игры

### Скриншоты/видяшка (если есть)
![image](https://github.com/26-chips/26-chips-pacman/assets/126918257/f71bfedb-08cb-465c-896a-3a9a65b18b8e)

### TBD (если есть)

Залью после появления дропдауна

2023-06-04 09:12 UTC, Futuringer approved these changes

2023-06-05 22:39 UTC, bin-umar commented
@gitnbrsp точно ли это твоя самая весомая задача в спринте?

2023-06-06 16:46 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

Реджектну ПР по причине того что у меня сомнения что это твоя самая весомая задача в спринте, так как у неё весь 1.

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/pages/MainPage/MainPage.tsx
> +export default MainPage as FunctionComponent;
Чтобы не писать as тебе надо было сразу указать соответствующий тип
```ts
const MainPage: FunctionComponent = () => {
```

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <div className={styles.header}>
Советую называть классы по [БЭМ](https://ru.bem.info/methodology/quick-start/#%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%BD%D0%B8%D0%B5)-у: `container`, `container__header`

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/pages/MainPage/MainPage.tsx
> +        <div className={styles.menu}></div>
для чего нужен пустой див?

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/pages/MainPage/MainPage.tsx
> +          }}></Switch>
```suggestion
        <Switch
          checked={theme}
          onChange={() => {
            toggleTheme(!theme);
          }} />
```
И лучше будет вынести onChange в отдельную функцию, инлайн функции не очень хороши для производительности ререндера. Конечно это экономия на спичках, но хорошая практика.

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/pages/MainPage/mainPage.module.scss
> +  width: 90%;
Чисто из любопытства, почему ширина хедера 90%? Мне кажется должен быть 100, нет?

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/styles.module.scss
>    background: $black;
**Не касается текущего ПР-а. Коммент относиться в целом к проекту,**

Не очень правильно назвать переменных такими именам. В чём смысл наименовать переменные по названиям цветов? Ведь их также можно использовать напрямую и без переменных.

Основной смысл этих переменных это выделение цветов в дизайн-токены. А смысл дизайн токенов в том чтобы в случае редизайна или изменения конкретного значения токена изменился бы в одном месте.
То есть задача состоит не в том чтобы все белые цвета перевести в одну переменную, черные во вторую, и т.д. Потому что например мы можем использовать белый цвет как background, так и в качестве цвет текста основного наших кнопок. В таком случае совершенно валидно и правильно разделить их в две разные переменные:
- colorBg
- colorButtonText
Иными словами не стоит группировать по значению, так как это бессмысленно, а надо по css свойствам.

В качестве примера можешь посмотреть https://paradigm.mail.ru/design_tokens/colors, можешь на его примере убедиться что белый цвет например используется в трёх разных токенах.

Ну и в целом рекомендую прочитать про [дизайн-токенов](https://paradigm.mail.ru/design_tokens).

2023-06-06 16:46 UTC, bin-umar commented on packages/client/src/App.test.tsx
>  // @ts-ignore
Лучше использовать [ts-expect-error](https://manual.typescript.pp.ua/pages/what-is-new/3.9/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%BD%D0%B0%D1%8F%20%D0%B4%D0%B8%D1%80%D0%B5%D0%BA%D1%82%D0%B8%D0%B2%D0%B0%20@ts-expect-error/content.html), чтобы линтер не ругался

2023-06-06 20:25 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/MainPage.tsx
> +export default MainPage as FunctionComponent;
Ок, спасибо, учту. По поводу веса задач вроде как специально ведется бэклог в linear, по крайней мере куратор в курсе и там можно посмотреть у кого что за задачи были за спринт, во всяком случае я думал это так организовано

2023-06-06 20:28 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/MainPage.tsx
> +        <div className={styles.menu}></div>
Забыл убрать, была заглушка, спасибо

2023-06-06 20:33 UTC, gitnbrsp commented on packages/client/src/App.test.tsx
>  // @ts-ignore
Ок, спасибо, учту. Но вообще это код шаблона, можешь оформить Issue (https://github.com/yandex-praktikum/client-server-template-with-vite/blob/main/packages/client/src/App.test.tsx)

2023-06-06 20:35 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/MainPage.tsx
> +      <div className={styles.header}>
Ну тут вроде как общий контейнер, а не только хедера, поэтому мне показалось это немного неуместным. Но за замечание спасибо, лишний раз посмотрел БЭМ

2023-06-06 21:11 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/mainPage.module.scss
> +  width: 90%;
Да, ты прав, по хорошему надо было бы положить в контейнер и задать отступы, но это самый простой способ что пришел в голову чтобы быстро отодвинуть инпут, который улетал за край. Позже планировалось заменить на компонент готовый, который сейчас в работе

2023-06-06 21:32 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/MainPage.tsx
> +export default MainPage as FunctionComponent;
Экспорт оставил пока без изменений чтобы соответствовать остальным страницам

2023-06-07 07:29 UTC, bin-umar commented on packages/client/src/App.test.tsx
>  // @ts-ignore
Не касается конкретно твоего ПР-а, в целом совет.

2023-06-07 07:31 UTC, bin-umar commented on packages/client/src/pages/MainPage/MainPage.tsx
> +export default MainPage as FunctionComponent;
> По поводу веса задач вроде как специально ведется бэклог в linear, по крайней мере куратор в курсе и там можно посмотреть у кого что за задачи были за спринт, во всяком случае я думал это так организовано

У ревьюеров нет доступа к вашему linear-у, поэтому и спрашиваю. https://github.com/26-chips/26-chips-pacman/pull/26#issuecomment-1577575855

2023-06-07 07:36 UTC, bin-umar commented on packages/client/src/pages/MainPage/MainPage.tsx
> +export default MainPage as FunctionComponent;
> Экспорт оставил пока без изменений чтобы соответствовать остальным страницам

А если вам понадобиться добавить пропсы, то будете их в конце странице к `as` их написать?
```ts
export default MainPage as FunctionComponent<Props>;
```

`as` предназначен для других целей, в ситуациях конкретно тип можно конкретно указать, то указывается сразу. Не знаю от куда к вам пришла идея писать типы через as в конце.

2023-06-07 16:19 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/MainPage.tsx
> +export default MainPage as FunctionComponent;
> > По поводу веса задач вроде как специально ведется бэклог в linear, по крайней мере куратор в курсе и там можно посмотреть у кого что за задачи были за спринт, во всяком случае я думал это так организовано
> 
> У ревьюеров нет доступа к вашему linear-у, поэтому и спрашиваю. [#26 (comment)](https://github.com/26-chips/26-chips-pacman/pull/26#issuecomment-1577575855) Если ответ да, давай тогда продвинем ПР дальше.

Ответ да, переотправил ссылку

2023-06-07 16:30 UTC, bin-umar approved these changes

2023-06-10 09:13 UTC, Abricos78 approved these changes

2023-06-10 09:50 UTC, merged