Feature/PRA-13 Error page
26-chips/26-chips-pacman pull request #27
Opened 2023-06-03 11:36 UTC by gitnbrsp

### Какую задачу решаем
Страница ошибки 

### Скриншоты/видяшка (если есть)
<details> 
  <summary>Скриншоты</summary>
   
![Screenshot from 2023-06-03 13-31-48](https://github.com/26-chips/26-chips-pacman/assets/126918257/dcc1754f-bb17-4b09-a822-026c75a5cbe3)
![Screenshot from 2023-06-03 13-32-02](https://github.com/26-chips/26-chips-pacman/assets/126918257/f72a94ae-d1bb-472b-8e31-b9cfc8ee2e3a)
![Screenshot from 2023-06-03 13-32-10](https://github.com/26-chips/26-chips-pacman/assets/126918257/f79925d7-e2a4-4ec2-904f-0e491bf90b8c)

</details>

### TBD (если есть)

Добавил динамически изменющуюся картинку через внешний API https://www.dicebear.com/styles/thumbs, лицензия открытая СС 1.0, никто не должен быть против (https://www.dicebear.com/styles/thumbs#details)
И пока оставил одним компонентом с передачей текста и кода ошибки, если будет мешать - заменю на 2 полноценных страницы

2023-06-04 18:52 UTC, gitnbrsp commented on packages/client/src/assets/img/Error.svg
ок, сейчас уберу

2023-06-04 18:54 UTC, gitnbrsp commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +      <div className={styles.errorCode}>{statusCode}</div>
не хотел сбрасывать стили)

2023-06-04 19:42 UTC, gitnbrsp commented on packages/client/src/pages/ErrorPage/ErrorPage.tsx
> +        src={apiLink}
подумал так будет интересней, заменил

2023-06-04 19:53 UTC, gitnbrsp commented on packages/client/src/pages/MainPage/MainPage.tsx
> +  const [theme, toggleTheme] = useState(false);
ну да это пока заглушка, сначала была строкой, потом поменял на булевую, а название забыл. Да и вообще компонент другой, случайно в ветку попал)

2023-06-06 16:05 UTC, Futuringer requested changes
![image](https://github.com/26-chips/26-chips-pacman/assets/77829629/4c61abe3-e2de-439c-9212-c53134d1815c)
нужно перетасовать компоненты, сейчас призрак живет отдельной жизнью и часто уплывает от контейнера с текстом + контейнер с текстом спозиционирован марджином от верха экрана,  что приводит к тому, что на каких-то экранах он по центру, на каких-то выше центра, на каких-то он обрезан снизу, хотя мог бы поместиться.
Предлагаю сделать так:
* весь контейнер страницы это flex-container
* весь контент на странице (текста, кнопка, картинка) заключены в один контейнер, у которого margin:auto и который за счет того, что находится во flex-container будет всегда по центру. У этого контейнера position:relativ
* картинка тоже находится в этом контейнере, она абсолютно спозиционированна внутри этого контейнера согласно макету

2023-06-09 23:00 UTC, closed without merging