PRA-54 Tests
26-chips/26-chips-pacman pull request #41
Opened 2023-06-15 13:46 UTC by gitnbrsp

### Какую задачу решаем
Тесты для части компонентов и игрового движка 

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-15 14:36 UTC, juliastetskaya commented on packages/client/src/components/Button/Button.test.tsx
> +    render(mockComponent);
Вывоз функции render возвращает объект, содержащий вс проверки
const button = render(<Button>Default Button</Button>);
expect(button.getByText(.....)

И тогда тебе не нужен screen вообще

2023-06-15 14:37 UTC, juliastetskaya commented on packages/client/src/components/Button/Button.test.tsx
> +    expect(screen.getByText('Default Button')).toBeDefined();
`toBeDefined` проверяет, что переменная определена. В данном случае мы наверно хотим знать, что компонент кнопки отрендерился, поэтому больше подойдет матчер `toBeInTheDocument()`

2023-06-15 14:39 UTC, juliastetskaya commented on packages/client/src/components/Canvas/Canvas.test.tsx
> +    render(<CanvasComponent {...CanvasProps} />);
И как мы отсюда знаем, что компонент отрендерился? Проверки никакой нет

2023-06-15 14:40 UTC, juliastetskaya commented on packages/client/src/components/Canvas/Enemy.test.tsx
> +    expect(newPosition).not.toEqual(startPosition);
Думаю, стоит добавить проверку на то, что новая позиция та, которую мы ожидаем

2023-06-15 14:42 UTC, juliastetskaya commented on packages/client/src/components/Canvas/Map.test.tsx
> +export const mapStrStub = map.fillMapAsStrings(mapString);
Давай добавим отступы между строк, читать текст сплошником сложно

2023-06-15 19:43 UTC, gitnbrsp commented on packages/client/src/components/Canvas/Enemy.test.tsx
> +    expect(newPosition).not.toEqual(startPosition);
Задумка была в том, что нас не интересует насколько персонаж сдвинулся, важен только факт того что он сдвинулся, так как может измениться скорость или еще что-то. Можно сделать отдельный тест на скорость передвижения если это важно

2023-06-15 21:34 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/GamePage.test.tsx
> +import '@testing-library/jest-dom';
добавил, но она нужна только в тестах компонентов, разве нет?

2023-06-16 07:11 UTC, Futuringer requested changes

2023-06-16 07:11 UTC, Futuringer commented on packages/client/src/tests/helpers.test.tsx
> +      expect(pathCycleStub).toBeDefined();
Тест пройдет, если функция хоть что-то вернет, не обязательно путь и не обязательно цикличный. Самый осмысленный тест тут был бы , что если мы берем результат работы функции был бы таким
const test = (arr) => {
  for (let i = 0; i < arr.length/2; i++) {
    if (arr[arr.length/2-1-i] !== arr[arr.length/2+i]) 
      {
        return false
      }
  }
  
  return true
}

только нужно проверять не на равенство, а на то, что у этих элементов противоположный путь, а количество шагов совпадает.
Ну или можно упростить и просто проверить некоторые члены массива по этому принципу, например первый и последний, второй и предпоследний...

2023-06-17 07:20 UTC, Futuringer approved these changes

2023-06-17 16:09 UTC, Olegas requested changes
В PR сказано что тут должны быть тесты компонентов и тесты игрового движка.
Тесты компонентов - увидел, ок
Тесты игрового движка - не увидел (возможно не понял что это они). Ожидал увидеть какие-то тесты логики, например персонаж столкнулся с привидением - игра окончена, персонаж съел последнюю фишку - вы выиграли и т.п.

2023-06-17 16:09 UTC, Olegas commented on packages/client/src/tests/__snapshots__/EndGameScreen.test.tsx.snap
> +            className="undefined undefined undefined"
Это разве нормально? Разве должны быть такие классы на элементе?

2023-06-17 22:53 UTC, gitnbrsp commented on packages/client/src/tests/EndGameScreen.test.tsx
> +    const tree = create(<EGSMock />).toJSON();
Ок, спасибо, поправлю. 

Подскажи пожалуйста по поводу того какие тесты нужно добавить по твоему мнению. Просто классы игровых персонажей (Pacman, Enemy), Canvas, вспомогательные функции из helpers на мой взгляд относятся к движку. Было бы понятней что тестировать, если бы были какие-то конкретные требования, но в бэклоге про это ни слова. Тестов _персонаж столкнулся с привидением - игра окончена, персонаж съел последнюю фишку - вы выиграли_ будет достаточно или еще что-то нужно?

2023-06-17 22:56 UTC, gitnbrsp commented on packages/client/src/tests/__snapshots__/EndGameScreen.test.tsx.snap
> +            className="undefined undefined undefined"
Не заметил, спасибо, поправлю

2023-06-20 19:55 UTC, Olegas commented on packages/client/src/tests/EndGameScreen.test.tsx
> +    const tree = create(<EGSMock />).toJSON();
@gitnbrsp Я еще раз пересмотрел тесты и понял, почему мне показалось недостаточным проверить Pacman и Enemy. Я не увидел там проверки логики. Увидел простой тест - у элемента есть начальное состояние. Но какой-то логики, какого-то изменения состояния в ответ на какие-то действия - не увидел.

В общем виде - хочется увидеть какие-то тесты вида "выполнили какое-то действие над объектом, его состояние изменилось с А на Б". 

Потому что обычно проблемы как раз бывают с логикой, инкапсулированной в объектах.

2023-06-23 17:35 UTC, Olegas approved these changes
👍

2023-06-25 18:33 UTC, merged