PRA-50 Service Worker
26-chips/26-chips-pacman pull request #45
Opened 2023-06-17 13:52 UTC by Abricos78

### Какую задачу решаем
Добавил Service Worker

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-06-18 15:20 UTC, Futuringer approved these changes

2023-06-19 11:58 UTC, bin-umar commented on packages/client/public/sw.js
> +  'index.html'
Почему тут только index.html? js,css файлы не планируете кешировать? В целом статику

2023-06-19 12:01 UTC, bin-umar commented on packages/client/public/sw.js
> +  if (url.origin === location.origin) event.respondWith(cacheFirst(request));
У вас бэкенд другой origin?

2023-06-19 12:06 UTC, bin-umar commented on packages/client/public/sw.js
> +    await cache.put(request, response.clone());
Не стоит кешировать все запросы, лучше кешировать только статику чтобы не заполнить кеш ненужными данными.

2023-06-19 12:08 UTC, bin-umar commented on packages/client/public/sw.js
> +  else event.respondWith(networkFirst(request));
Немного придирки конечно, но лучше всё-таки добавить фигурные скобки и отступ между логическими блоками. Так код читабельнее.
```suggestion
  const { request } = event;
  const url = new URL(request.url);

  if (url.origin === location.origin) {
    event.respondWith(cacheFirst(request));
  } else {
    event.respondWith(networkFirst(request));
  };
```

2023-06-19 12:22 UTC, bin-umar commented on packages/client/public/sw.js
> +  'index.html'
Вижу ниже что кешируете их динамически. Минус такого подхода в том что у тебя статические файлы будут даваться с кеша уже с третьего раза. Первый раз устанавливается сервис-воркер, второй раз кеширует, и только третий раз даёт из кэша.

Поэтому тут необходимо указать статические файлы, этого можно добиться разными способами. Либо во время бандла, либо уже в рантайм, либо руками (менее удобный). Предлагаю поресерчит и добавить сюда список статических файлов.

2023-06-19 12:24 UTC, bin-umar commented on packages/client/public/sw.js
> +    return cached || {};
вместо {} лучше добавить какой-нибудь ответ через которого приложение понимает что он в режиме оффлайн, в идеале ещё и показывает оффлайн страницу.

2023-06-19 12:26 UTC, bin-umar commented on packages/client/public/sw.js
> +  if (url.origin === location.origin) event.respondWith(cacheFirst(request));
Сюда ещё стоит добавить игнорирование не http запросов (запросы расширешений)
```ts
  if (!request.url.startsWith('http')) {
    return;
  }
```

2023-06-19 12:26 UTC, bin-umar commented on packages/client/public/sw.js
> +  if (url.origin === location.origin) event.respondWith(cacheFirst(request));
Можно ещё игнорировать POST запросы, так как мы по любому это некешируемые запросы.

2023-06-19 12:28 UTC, bin-umar requested changes
Привет! Я ревьюер из Я.Практикума.

В целом код написан в читабельном виде. Прощу учесть оставленные комменты и починить. Особо волнует случай с кешируемыми файлами и кеширование всех запросов подряд (должны кешировать только нужные, остальные стоит игнорировать). Оффлайн страницу можно и потом.

2023-06-20 16:29 UTC, Abricos78 commented on packages/client/public/sw.js
> +  'index.html'
Решение больше похоже на костыль, чем на системный подход. Но ничего лучше я найти не смог, если есть возможность скинуть ссылки на другие варианты реализации, то с удовольствием посмотрел бы как это можно сделать по другому

2023-06-20 21:15 UTC, bin-umar commented on packages/client/public/sw.js
> +  'index.html'
Ребята из другой команды сделали такое решение https://github.com/fastPaws-game/fast-paws/pull/34/files

2023-06-20 21:19 UTC, bin-umar commented on packages/client/public/sw.js
> +  'index.html'
Когда-то давно я нашёл такой способ https://stackoverflow.com/questions/46830493/is-there-any-way-to-cache-all-files-of-defined-folder-path-in-service-worker/55543550

2023-06-23 20:42 UTC, merged