PRA-56 Fullscreen Web API
26-chips/26-chips-pacman pull request #46
Opened 2023-06-17 22:21 UTC by gitnbrsp

### Какую задачу решаем
Добавить Fullscreen Web API

### Скриншоты/видяшка (если есть)
![image](https://github.com/26-chips/26-chips-pacman/assets/126918257/9624f33c-75ef-44ea-9cb7-e71d107ca1a4)

### TBD (если есть)

2023-06-18 08:44 UTC, Futuringer requested changes

2023-06-18 08:44 UTC, Futuringer commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
>        <div>
этому контейнеру нужно добавить position static и z-index чтобы мы могли кликать на икону свертывания/развертывания когда игра на паузе или идет отсчет

2023-06-18 08:44 UTC, Futuringer commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
> +  document.addEventListener('keydown', e => {
навешиваем лисенеры в useEffect, в return очищаем их

2023-06-18 16:14 UTC, kris-alexwa commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
> +            />
Мне больше нравится запись: `<img  className={styles.fullscreenIcon} src={ isFullscreen ? expand : shrink} alt="fullscreen switch" />`
Ну или alt по аналогии с src менять - не принципиально.
Вкусовщина, возможно, но так можно избавиться от копипасты и написать эту часть в 1-2 строки

2023-06-19 08:03 UTC, juliastetskaya requested changes

2023-06-19 08:03 UTC, juliastetskaya commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
> +  const isFullscreenDisabled = !document.fullscreenEnabled;
Предлагаю вынести всю логику по фуллскрину в отдельный хук useFullscreen. Этот файл итак содержит много другой логики

2023-06-19 17:29 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
>        <div>
только с absolute почему-то получилось, с остальными перекрывает  оверлеем

2023-06-19 17:31 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
> +    if (e.keyCode === 27 || e.keyCode === 122) {
почему-то показалось что чтобы снять fullscreen нужно esc тоже детектить, а он и так снимает

2023-06-19 17:31 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
> +  const isFullscreenDisabled = !document.fullscreenEnabled;
это вроде обсуждали на созвоне, вынес в компонент чтобы не мозолило глаза

2023-06-19 17:41 UTC, kris-alexwa approved these changes

2023-06-19 17:59 UTC, juliastetskaya commented on packages/client/src/pages/GamePage/Components/FullscreenButton.tsx
> +      if (e.key === '27') {
У свойства `key` значения по названиям клавиш, не цифры

2023-06-19 18:02 UTC, juliastetskaya commented on packages/client/src/pages/GamePage/Components/FullscreenButton.tsx
> +      window.removeEventListener('keydown', handleFSKey);
Почему навешиваем на `document`, а удаляем с `window`?

2023-06-19 18:02 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/FullscreenButton.tsx
> +      if (e.key === '27') {
спасибо, поправил

2023-06-19 18:11 UTC, juliastetskaya approved these changes

2023-06-19 18:15 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/FullscreenButton.tsx
> +      window.removeEventListener('keydown', handleFSKey);
не заметил, спасибо

2023-06-19 19:20 UTC, merged