PRA-63 MediaAPI
26-chips/26-chips-pacman pull request #61
Opened 2023-06-29 00:38 UTC by gitnbrsp

### Какую задачу решаем
Добавление звуков для  игры

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-01 10:23 UTC, Futuringer requested changes

2023-07-01 10:23 UTC, Futuringer commented on packages/client/src/pages/GamePage/Components/SoundButton.tsx
> +  const [isMuted, mute] = useState(false);
предлагаю называть по стандарту useState, те isMuted, setIsMuted

2023-07-01 10:23 UTC, Futuringer commented on packages/client/src/assets/sounds/countdown.mp3
не используется, удалить или добавить звук отсчету

2023-07-01 10:23 UTC, Futuringer commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +import bonusSound from 'assets/sounds/bonus.mp3';
не добавлен файл

2023-07-01 10:23 UTC, Futuringer commented on packages/client/src/pages/GamePage/Components/GameBlock.tsx
> +  useEffect(() => {
useEffect без dependency, срабатывает на изменение всего, что можно, предлагаю добавить в dependency isPaused, и в зависимости от значения делать AudioElements.gameLoop.pause(); или AudioElements.gameLoop.play();

2023-07-01 15:16 UTC, gitnbrsp commented on packages/client/src/assets/sounds/countdown.mp3
удалил

2023-07-01 17:30 UTC, Futuringer approved these changes

2023-07-02 08:51 UTC, IvanPeleshok commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +        // @ts-ignore
Судя по коду, игнорировать необходимо тот момент, что this.audio может быть null
В данном случае, предлагаю, либо добавить этот шаг в условие (ts это учтёт - ошибка уйдёт), либо добавить оператор "!" (this.audio!.cloneNode(true).play()

2023-07-02 08:52 UTC, IvanPeleshok commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +      // @ts-ignore
Избавиться от // @ts-ignore (сверху написал как)

2023-07-02 08:52 UTC, IvanPeleshok requested changes
Есть замечания

2023-07-02 08:54 UTC, IvanPeleshok commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +const win = new Sound(winSound, false, 0.5);
Предлагаю конфигурацию вынести в отдельный модуль

2023-07-02 14:54 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +        // @ts-ignore
здесь не из-за этого, тремя строчками выше проверяется что this.audio существует, но исправил

2023-07-02 14:58 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +      // @ts-ignore
убрал, оператор "!" не самый лучший вариант исправления, вот тут написано почему https://rules.sonarsource.com/typescript/RSPEC-2966/

2023-07-02 15:06 UTC, gitnbrsp commented on packages/client/src/pages/GamePage/Components/Sound.ts
> +const win = new Sound(winSound, false, 0.5);
вынес

2023-07-02 15:40 UTC, IvanPeleshok approved these changes

2023-07-03 18:49 UTC, merged