Feature/pra 59 ssr conflict
26-chips/26-chips-pacman pull request #66
Opened 2023-07-06 08:16 UTC by Abricos78

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-07-09 08:46 UTC, gitnbrsp commented on packages/server/index.ts
> +  app.use(cors());
Эту штуку не нужно конфигурировать на конкретные урлы случайно? Не замечание, просто вопрос, сходу не разобрался, но CORS ведь не просто так блочится. Пример из документации https://www.npmjs.com/package/cors
```
var whitelist = ['http://example1.com', 'http://example2.com']
var corsOptions = {
  origin: function (origin, callback) {
    if (whitelist.indexOf(origin) !== -1) {
      callback(null, true)
    } else {
      callback(new Error('Not allowed by CORS'))
    }
  }
}
```

2023-07-09 08:46 UTC, gitnbrsp commented on packages/client/package.json
> +    "build:ssr": " rimraf ./ssr-dist && tsc && vite build --config ssr.config.ts",
А оно разве не должно в этой папке само перезаписываться при билде?

2023-07-09 08:46 UTC, gitnbrsp commented on packages/client/src/components/ErrorBoundary/index.tsx
> +        return <ErrorPage {...errorProps404} />;
Этот компонент по умолчанию возвращает 404, можно не передавать пропсы

2023-07-09 08:46 UTC, gitnbrsp commented on packages/server/index.ts
> +  // createClientAndConnect();
это нам скоро понадобится)

2023-07-09 08:46 UTC, gitnbrsp commented on packages/client/src/App.tsx
> +  const [firstRender, setFirstRender] = useState(true);
так и не понял зачем это, подскажи пожалуйста

2023-07-09 08:50 UTC, Abricos78 commented on packages/server/index.ts
> +  // createClientAndConnect();
Меня там раздражал error поэтому закомментировал

2023-07-09 08:53 UTC, Abricos78 commented on packages/client/src/components/ErrorBoundary/index.tsx
> +        return <ErrorPage {...errorProps404} />;
У меня на это ругался ts, что нет обязательных полей. Впринципе можно их сделать тогда необязательными в ErrorPage

2023-07-09 09:03 UTC, Abricos78 commented on packages/client/package.json
> +    "build:ssr": " rimraf ./ssr-dist && tsc && vite build --config ssr.config.ts",
У меня в папке ssr-dist файлы перезаписываются, но не удаляются файлы со старой сборки, поэтому принудительно папку удаляю

2023-07-10 16:47 UTC, juliastetskaya requested changes

2023-07-10 17:03 UTC, juliastetskaya approved these changes

2023-07-12 18:21 UTC, gitnbrsp approved these changes

2023-07-12 18:37 UTC, Olegas approved these changes

2023-07-12 19:09 UTC, merged