Add SSR router and store
26-chips/26-chips-pacman pull request #67
Opened 2023-07-13 20:04 UTC by juliastetskaya

### Какую задачу решаем
Добавляет работу со стором и роутер на серверной стороне

2023-07-15 08:58 UTC, Abricos78 approved these changes

2023-07-15 10:36 UTC, gitnbrsp approved these changes

2023-07-15 19:18 UTC, Olegas requested changes
Добрый вечер. 
Есть одно серьезное замечание, указал в комментарии.
Нужно исправить

2023-07-15 19:18 UTC, Olegas commented on packages/server/index.ts
> +        .replace('<!--store-data-->', initStateSerialized);
Здесь серьезная ошибка. Место для эксплуатации уязвимости типа XSS. Стейт при передаче в страницу нужно соответствующим образом заэкранировать. 
Посмотрите тут за подробностями: https://redux.js.org/usage/server-rendering#inject-initial-component-html-and-state

2023-07-16 05:56 UTC, juliastetskaya commented on packages/server/index.ts
> +        .replace('<!--store-data-->', initStateSerialized);
Добавила экранирование, спасибо

2023-07-16 09:21 UTC, Olegas approved these changes

2023-07-16 09:25 UTC, merged