PRA-71 Add docker
26-chips/26-chips-pacman pull request #73
Opened 2023-07-19 23:07 UTC by gitnbrsp

### Какую задачу решаем

- Сервер и базы должны быть «обёрнуты» в Docker.
- Между сервисами в docker-compose должны быть корректные зависимости.
- Явки / пароли должны добавляться в проект через env.

Добавил на входящие запросы nginx реверс прокси, через который перенаправляются все запросы в остальные контейнеры, далее на этом nginx можно будет добавить сертификаты и т.д.

TODO:
- перенести postgres на localhost
- перенести конфиг nginx из клиента в nginx-proxy
- оставить либо раздачу статики либо SSR

### Скриншоты/видяшка (если есть)

![image](https://github.com/26-chips/26-chips-pacman/assets/126918257/f53e8ca0-60b9-4ad2-bbf3-c6c4ab9b3d81)

### TBD (если есть)

2023-07-23 13:34 UTC, Futuringer approved these changes

2023-07-23 16:10 UTC, Olegas requested changes
Добрый день. Есть замечания по реализации. 
1. Не понимаю зачем nginx в том виде, как сейчас настроено. Подробнее написал в комментарии
2. Плохо, что после текущего PR сломается oAuth. Выполнение новых задач не должно портить приложение, ранее реализованный функционал не должен ломаться.

Надо переделать.

2023-07-23 16:10 UTC, Olegas commented on nginx_proxy.conf
> +}
А для чего нужен nginx, если все равно все части приложения остались на своих собственных портах и точек входя в приложение по прежнему две? Какую задачу он решает? Может уже если делать proxy так хотя бы пусть тогда приложение будет на одной паре host:port а nginx внутри уже раскидывает по серверам на основе URL?

2023-07-23 16:10 UTC, Olegas commented on packages/client/src/utils/consts.ts
> +// todo fix oauth
Что значит этот комментарий? После эти изменений сломается oauth? По хорошему надо чинить сразу. PR не должен ухудшать функциональность приложения.

2023-07-23 17:57 UTC, gitnbrsp commented on nginx_proxy.conf
> +}
Добрый вечер, nginx нужен для одной точки входа для апи и сайта, в дальнейшем хотел разделить сервер api и сервер ssr и обращаться к ним через один nginx. Его конфигурирование все равно висит в бэклге следующего спринта. БД перевешена на localhost для дебага в основном и на сервере эту точку входа можно будет убрать и наружу будет только nginx. Сейчас он только проксирует на статику и сервер, вы правы, но порты самих контейнеров с сервером и статикой снаружи должны быть недоступны.

2023-07-23 18:22 UTC, gitnbrsp commented on packages/client/src/utils/consts.ts
> +// todo fix oauth
На данный момент oauth работает, но только на статике, на 3000 порту, а апи с ssr на 3001, это просто напоминание на 9 спринт о том что тут должен быть редирект на доменное имя, задача в бэклоге 9 спринта, как и конфиг nginx. Сейчас можно перевесить на порт 3001 или использовать переменную окружения, но не вижу смысла так как потом все равно менять

2023-07-24 18:11 UTC, Olegas approved these changes
Ок, понял. Принято

2023-07-26 19:28 UTC, merged