PRA-72 connect forum api and ui
26-chips/26-chips-pacman pull request #74
Opened 2023-07-22 11:25 UTC by Abricos78

### Скриншоты/видяшка (если есть)
![Скриншот 22 07 23_13 42 45](https://github.com/26-chips/26-chips-pacman/assets/67517869/752759b1-fb6a-4a14-9420-9c6cf88b94e1)
![Скриншот 22 07 23_14 08 28](https://github.com/26-chips/26-chips-pacman/assets/67517869/4eaad5f7-b517-4736-bf3b-bbe477e34c23)

2023-07-22 14:17 UTC, juliastetskaya commented on packages/client/src/api/forumApiSlice.ts
> +import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/dist/query/react';
Мы точно должны импортировать из папки dist?

2023-07-22 14:18 UTC, juliastetskaya commented on packages/server/api/db.ts
> +  password: POSTGRES_PASSWORD || 'postgres',
Думаю, по соображениям безопасности не стоит прописывать дефолтное значение для `password`

2023-07-22 14:59 UTC, Abricos78 commented on packages/server/api/db.ts
> +  password: POSTGRES_PASSWORD || 'postgres',
Поправил

2023-07-23 13:58 UTC, gitnbrsp commented on packages/server/api/db.ts
> +  password: POSTGRES_PASSWORD || 'postgres',
Я бы наоборот оставил. Если вывести порт БД на белый ip сервера, то его с дефолтным значением все равно подберут за полчаса боты, они стучатся на все открытые порты и знают все дефолтные пароли) А если убрать порт на localhost сервера, то даже с дефолтным паролем никто туда не зайдет не попав на сервер. Ну или если убирать, тогда можно все значения по умолчанию убрать, так как без пароля в env на локальный постгрес не войдет все равно. Но на мой взгляд с дефолтными значениями удобнее дебажить, главное их потом не забыть заменить

2023-07-25 19:52 UTC, Olegas requested changes
Добрый вечер.
В целом хорошо, но есть замечания к организации кода.
1. В некоторых местах нет обработчик ошибок
2. В некоторых местах обработка ошибок есть, но она крайне странная (поймать и выкинуть снова без изменений)
3. Мелкие замечания типа оставленного закомментированного кода
+1 совет по работе с датой (как форматировать нативными функциями).

Оставил комментарии в конкретных местах кода.

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumChatPage/components/messageLayout/index.tsx
> +// import { EmojiButton } from '../emojiButton';
Не оставляйте закоментированный код, это замусоривает код проекта

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumChatPage/index.tsx
> +  'декабря',
Посмотри на Date#toLocaleDateString
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

```
var options = { year: 'numeric', month: 'long', day: 'numeric' };
var today  = new Date();

console.log(today.toLocaleDateString('ru-RU', options));
// 25 июля 2023 г.
```

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumChatPage/index.tsx
> +// ];
Тут тоже явно лишний код

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumChatPage/index.tsx
> +    const { messages, users } = await getAllComments(chatId).unwrap();
Думаю тут стоит обработать возможную ошибку загрузки

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumChatPage/index.tsx
> +      throw new Error(error as string);
А зачем нужна обработка ошибки, которая просто выбрасывает ту же ошибку, что и была поймана и не делает ничего другого?

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumChatPage/index.tsx
> +                  const currentDate = new Date(createdAt).getDate();
new Date(createdAt) - несколько раз. Явно надо вынести в переменную

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumPage/components/createTopic/index.tsx
> +      throw new Error(error as string);
Зачем обработка ошибки, которая ничего не делает? Если что, try/finally тоже вполне рабочая конструкция

2023-07-25 19:52 UTC, Olegas commented on packages/client/src/pages/ForumPage/components/forumTopicsTable/index.tsx
>    };
А зачем делать новую функцию? Почему вместо handleCreateTopic просто сразу не позвать handleChangeCreateTopic?

2023-07-25 19:52 UTC, Olegas commented on packages/server/api/services/TopicService.ts
> +      return await Topic.findAll({
return await - эта конструкция не имеет смысла. Для чего это сделано?

2023-07-25 19:52 UTC, Olegas commented on packages/server/api/services/TopicService.ts
> +      return await Topic.findAll({
Ниже снова обработка ошибки которая не делает ничего. Почему просто не дать исключению вылететь дальше? Зачем его ловить и перевыбрасывать заново?

2023-07-26 17:23 UTC, Olegas requested changes
Стало лучше, но не везде.
Смотри, был вот такой код
```
try {
      setIsLoading(true);
      await createTopic({ title }).unwrap();
      handleCancel();
    } catch (error) {
      throw new Error(error as string);
    } finally {
      setIsLoading(false);
    }
```
Что тут хорошо: обрабатывается ошибка от асинхронного createTopic, в случае ее возникновения состояние isLoading возвращается в правильное состояние в finally
Что тут странно: catch() который не делает ничего, ты ловишь ошибку и снова ее выбрасываешь.

Мое замечание было не к тому, что надо везде убрать обработку ошибок. Смысл был в том, что catch() { throw new Error() } - не имеет никакого смысла. Потому что ты ловишь ошибку, и сразу же ее же выкидываешь дальше.

Как правильно:

```
try {
      setIsLoading(true);
      await createTopic({ title }).unwrap();
      handleCancel();
    } finally {
      setIsLoading(false);
    }
```
Просто убери блок catch. При возникновении ошибки она вылетит дальше, но при этом состояние isLoading будет возвращено в правильное значение

2023-07-27 16:19 UTC, Olegas approved these changes
Супер! Работа принята

2023-07-29 09:09 UTC, merged