Add themes on the backend
26-chips/26-chips-pacman pull request #75
Opened 2023-07-22 20:55 UTC by juliastetskaya

### Какую задачу решаем
Бэкенд для темизации

2023-07-23 13:41 UTC, Futuringer approved these changes

2023-07-23 16:24 UTC, Olegas requested changes
Добрый день.
Все отлично, хорошо что учел все уникальные индексы в таблицах, что используешь upsert для вставки там, где могут быть конфликты. 👍
Есть вопрос по ThemeContextProvider - написал подробно комментарий в коде.
Нужно или исправить или объяснить, почему оно будет работать.

2023-07-23 16:24 UTC, Olegas commented on packages/client/src/contexts/ThemeContext.tsx
> +      const initialTheme = localStorage.getItem('theme') || THEMES.DARK;
А как это работает вместе с SSR? ThemeContextProvider строится и на SSR-стороне. Но на NodeJS нет localStorage API

2023-07-24 17:50 UTC, juliastetskaya commented on packages/client/src/contexts/ThemeContext.tsx
> +      const initialTheme = localStorage.getItem('theme') || THEMES.DARK;
По сути никак не работало. Вся работа по темизации производилась на стороне клиента. А поскольку  обращение к localStorage происходило исключительно в useEffect-ах, то и ошибок никаких не возникало.

Заменила localStorage на куки. Теперь если есть значение для темы в куках, оно подставляется на SSR-стороне. Спасибо за вопрос :)

2023-07-25 06:15 UTC, merged