PRA-73 Add CSP
26-chips/26-chips-pacman pull request #90
Opened 2023-08-07 18:21 UTC by kris-alexwa

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-08-09 08:28 UTC, Futuringer requested changes

2023-08-09 08:28 UTC, Futuringer commented on packages/server/lib/cfg.ts
> +    environmentConfig = require(path.join(CONFIG_DIR, ENV));
я так понимаю, тут мы определяем какой конфиг будет использоваться, может быть development а может быть production, нам не нужен файл production.ts рядом с development.ts?

2023-08-09 17:30 UTC, kris-alexwa commented on packages/server/lib/cfg.ts
> +    environmentConfig = require(path.join(CONFIG_DIR, ENV));
Добавила

2023-08-11 06:09 UTC, Futuringer approved these changes

2023-08-11 13:53 UTC, merged